# Generated by Django 4.0.5 on 2022-10-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('to do', 'to do'), ('in progress', 'in progress'), ('completed', 'completed')], max_length=20, null=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('importancy', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('importancy__gte', 1), ('importancy__lte', 10)), name='A qty value is valid between 1 and 10'),
        ),
    ]
