# Generated by Django 4.0.5 on 2022-10-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_organiser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='A qty value is valid between 1 and 10',
        ),
    ]
