# Generated by Django 4.0.5 on 2022-10-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_organiser', '0003_task_users'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('importancy__gte', 1), ('importancy__lt', 10)), name='A importancy value is valid between 1 and 10'),
        ),
    ]
