# Generated by Django 4.0.5 on 2022-10-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_organiser', '0004_task_a importancy value is valid between 1 and 10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
    ]
