# Generated by Django 4.0.5 on 2022-10-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_organiser', '0009_message_friendsgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('reg', 'regular'), ('fr', 'friend_request'), ('gr', 'group_request')], max_length=20, null=True),
        ),
    ]
