# Generated by Django 4.0.5 on 2022-10-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_organiser', '0015_alter_appuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendsgroup',
            name='members',
            field=models.ManyToManyField(to='task_organiser.appuser'),
        ),
    ]
