# Generated by Django 4.0.5 on 2022-10-28 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_organiser', '0016_alter_friendsgroup_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_organiser.friendsgroup'),
        ),
    ]
